name: adapter-tests
on:
  workflow_call:
permissions:
  contents: read
jobs:
  check:
    name: adapter-tests
    runs-on: windows-2025
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-python
      - name: 离线检查
        shell: pwsh
        run: |
          & ./adapter/maa/.venv/Scripts/python.exe -m unittest discover -s adapter/maa/tests -v
